### ISSUE TITLE
drracket crash on wayland - SIGSEGV MAPPER si_code on addr (nil)

### ISSUE THREAD

**Issue by pranavk** [racket/drracket#249]
Not sure if this trace would be helpful but dumping what I found here, just in case it gives any hints. I found similar report here (#15) but upon looking at the stack trace there, the cause of the problem seems to be quite different. This crash seems to be due to wayland.

```
#0  0x00007f052019d53f in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f0520187895 in __GI_abort () at abort.c:79
#2  0x0000000000670439 in fault_handler ()
#3  0x00007f052033df70 in <signal handler called> () at /lib64/libpthread.so.0
#4  0x00007f05093cd5cb in wl_proxy_marshal () at /lib64/libwayland-client.so.0
#5  0x00007f05096eb043 in wl_surface_attach (y=0, x=0, buffer=<optimized out>, wl_surface=<optimized out>) at /usr/include/wayland-client-protocol.h:3458
#6  0x00007f05096eb043 in gdk_wayland_window_attach_image (window=window@entry=0x34337f0 [GdkWaylandWindow]) at gdkwindow-wayland.c:770
#7  0x00007f05096eb2ba in gdk_window_impl_wayland_end_paint (window=0x34337f0 [GdkWaylandWindow]) at gdkwindow-wayland.c:940
#8  0x00007f050969fb3b in gdk_window_end_paint_internal (window=window@entry=0x34337f0 [GdkWaylandWindow]) at gdkwindow.c:3021
#9  0x00007f050969fe88 in gdk_window_end_draw_frame (window=window@entry=0x34337f0 [GdkWaylandWindow], context=context@entry=0x92894a0 [GdkDrawingContext]) at gdkwindow.c:3289
#10 0x00007f0508d6406b in gtk_widget_render (widget=widget@entry=0x2f27f70 [GtkWindow], window=0x34337f0 [GdkWaylandWindow], region=<optimized out>) at gtkwidget.c:17545
#11 0x00007f0508c0e989 in gtk_main_do_event (event=<optimized out>) at gtkmain.c:1838
#12 0x000000000066dc48 in ffi_call_unix64 ()
#13 0x000000000066d60f in ffi_call ()
#14 0x000000000066705f in  ()
#15 0x0000000000667547 in  ()
#16 0x00007f05204f3487 in  ()
#17 0x0000000000000001 in  ()
#18 0xfffffffffffff440 in  ()
#19 0x00000000ffffffff in  ()
#20 0x00007f050ba915a0 in g_hash_table_lookup_node (hash_return=<synthetic pointer>, key=0x7f05085fdf48, hash_table=0x7f05085fdf10 = {...}) at ghash.c:379
#21 0x00007f050ba915a0 in g_hash_table_lookup (hash_table=0x7f05085fdf10 = {...}, key=0x7f05085fdf48) at ghash.c:1153
#22 0xfffffffffffff440 in  ()
#23 0x0000000000000001 in  ()
#24 0x00000001e5f23d78 in  ()
#25 0x0000000000000000 in  ()
```

This crash is quite rare; eg: this is the second time in last 30 days I am seeing this crash.

**Comment by pranavk** [comment]
DrRacket version is 7.1
