### ISSUE TITLE
Opening any file crashes DrRacket

### ISSUE THREAD

**Issue by bon** [racket/drracket#77]
Running DrRacket 6.6.0.4 on Linux. Opening _any_ file, be it Racket code, an image or whatever, crashes DrRacket.

When running DrRacket from the command line, it gives

```
SIGSEGV MAPERR si_code 1 fault on addr (nil)
Aborted (core dumped)
```

**Comment by rfindler** [comment]
Do you get a core file? If so, can you please provide a backtrace?

**Comment by bon** [comment]
Below is the backtrace of the core dump. Is this helpful? 

```
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f1af697104f in raise () from /usr/lib/libc.so.6
[Current thread is 1 (Thread 0x7f1ae393a700 (LWP 27540))]
(gdb) bt
#0  0x00007f1af697104f in raise () from /usr/lib/libc.so.6
#1  0x00007f1af697247a in abort () from /usr/lib/libc.so.6
#2  0x00000000006be499 in fault_handler ()
#3  <signal handler called>
#4  0x00000000006c9bd2 in GC_malloc_atomic ()
#5  0x000000000045925f in scheme_glib_log_message ()
#6  0x00007f1af1e9d6f4 in g_logv () from /usr/lib/libglib-2.0.so.0
#7  0x00007f1af1e9d90f in g_log () from /usr/lib/libglib-2.0.so.0
#8  0x00007f1ae3941a8f in ?? () from /usr/lib/gio/modules/libdconfsettings.so
#9  0x00007f1ae3944407 in ?? () from /usr/lib/gio/modules/libdconfsettings.so
#10 0x00007f1af1e96d1a in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#11 0x00007f1af1e970d0 in ?? () from /usr/lib/libglib-2.0.so.0
#12 0x00007f1af1e9717c in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#13 0x00007f1ae39444bd in ?? () from /usr/lib/gio/modules/libdconfsettings.so
#14 0x00007f1af1ebd345 in ?? () from /usr/lib/libglib-2.0.so.0
#15 0x00007f1af6ce3454 in start_thread () from /usr/lib/libpthread.so.0
#16 0x00007f1af6a267df in clone () from /usr/lib/libc.so.6
```

**Comment by mflatt** [comment]
@bon Sorry that it took so long, but that backtrace was helpful - thanks!
